const VIDEO="https://www.dropbox.com/scl/fi/45sbxwk9uftuwg2oh4cm2/Lenaxis-FR.mp4?rlkey=rg7ula361gbmitq31qpz9zdyv&raw=1",LOGO="https://www.dropbox.com/scl/fi/ijjfiy2el5xtbjjgni5m3/Lenaxis_LOGO.png?rlkey=ema5wb238vmw02y63vb8pfxp4&raw=1";
const MODULES=[
{id:"core",name:"CORE",phase:"Cartographier",tag:"Cartographiez vos risques",icon:"◆",logo:"https://www.dropbox.com/scl/fi/jasch3mt8zx20lm5up5dx/LENAXIS_CORE_Logo.png?rlkey=3ley9yvac1ylf88d6d86o8dfz&raw=1",poster:"https://www.dropbox.com/scl/fi/nrev126f80oo2w9sht98k/Interface_LENAXIS_Core_V2.png?rlkey=w17tq15gnlv0t5nvnq5bempkb&raw=1",start:80,end:95,desc:"Sites, zones, équipements, processus, flux, dépendances et risques réunis dans un modèle vivant.",features:["Sites, locaux et zones","Actifs et équipements","Risques et scénarios","Historique et dépendances"]},
{id:"watch",name:"WATCH",phase:"Identifier",tag:"Détectez et anticipez",icon:"◉",logo:"https://www.dropbox.com/scl/fi/lfviv2yq91fqeggpt9lxe/LENAXIS_WATCH_Logo.png?rlkey=q5512re9j2e8p24mnrg5so7tr&raw=1",poster:"https://www.dropbox.com/scl/fi/ry2cmzw571ev372136jkd/Interface_LENAXIS_Watch_V2.png?rlkey=24qropd81d38h2xs8kjljnzb5&raw=1",start:138,end:157,desc:"Veille continue des évolutions réglementaires, environnementales et contextuelles rapprochées des sites concernés.",features:["Veille multi-sources","Expositions géolocalisées","Signaux faibles","Alertes contextualisées"]},
{id:"audit",name:"AUDIT",phase:"Identifier",tag:"Démontrez et progressez",icon:"▤",logo:"https://www.dropbox.com/scl/fi/zq31g1dxrxsnaceyl8nxm/LENAXIS_AUDIT_Logo.png?rlkey=u4g75wez1k6tadk2v477sl85q&raw=1",poster:"https://www.dropbox.com/scl/fi/axt7yiovtc41e1j4jdaij/Interface_LENAXIS_Audit_V2.png?rlkey=9bgbgylgrlpoz4087mgrawpn4&raw=1",start:117,end:138,desc:"Audits terrain digitalisés, questionnaires sectoriels, preuves, constats et plans d’action dans un flux traçable.",features:["Questionnaires métier","Preuves terrain","CAPA et actions","Rapports et conformité"]},
{id:"matrix",name:"MATRIX",phase:"Évaluer",tag:"Priorisez vos risques",icon:"◇",start:52,end:68,desc:"Scoring matriciel multi-axes pour hiérarchiser les risques, simuler les scénarios et prioriser les actions.",features:["Prouty + Radar","Scoring multi-axes","Simulation","Priorisation"]},
{id:"stats",name:"STATS",phase:"Évaluer",tag:"Analysez et comparez",icon:"▥",start:100,end:114,desc:"Tendances, comparaisons inter-sites, benchmarks sectoriels, anomalies et évolutions temporelles consolidées.",features:["Tendances","Multi-sites","Benchmarks","Anomalies"]},
{id:"alerts",name:"ALERTS",phase:"Identifier",tag:"Soyez alerté au bon moment",icon:"!",start:140,end:153,desc:"Notifications actives sur accidents, évolutions réglementaires, risques locaux et signaux critiques.",features:["Notifications ciblées","Journal","Sources","Suggestion d’action"]},
{id:"livestream",name:"LIVESTREAM",phase:"Identifier + Évaluer",tag:"Auditez à distance en temps réel",icon:"▶",start:84,end:100,desc:"Audit terrain temps réel, vidéo multi-participants, annotation et assistance IA pour rapprocher expertise et terrain.",features:["WebRTC","Multi-participants","Annotation","Pré-remplissage AUDIT"]},
{id:"crisis",name:"CRISIS",phase:"Gérer la crise",tag:"Préparez et gérez",icon:"♢",logo:"https://www.dropbox.com/scl/fi/7qektjanvxgbo3b62r0m3/LENAXIS_CRISE_Logo.png?rlkey=nu6no80mcmz41xwltw9gw1tlg&raw=1",poster:"https://www.dropbox.com/scl/fi/0t27pvrrro44vzn29b9bm/Interface_LENAXIS_Crise_V2.png?rlkey=lccozqjwh2128r8p6ydlhbmhg&raw=1",start:157,end:177,desc:"Activation et pilotage d’une cellule de crise : journal, carte tactique, rôles, décisions et communications.",features:["Activation rapide","Journal de crise","Carte tactique","Coordination"]},
{id:"dashboard",name:"DASHBOARD",phase:"Suivre",tag:"Pilotez en temps réel",icon:"▦",start:0,end:14,desc:"Tableaux de bord temps réel pour la direction, les opérations, la conformité et le reporting.",features:["KPIs","Multi-sites","Reporting","API BI"]},
{id:"flotte",name:"FLOTTE",phase:"Identifier + Évaluer",tag:"Maîtrisez le risque routier",icon:"↗",start:14,end:28,desc:"Véhicules, conducteurs, sinistres, comportements de conduite et actions de prévention.",features:["Véhicules","Conducteurs","Sinistres","Prévention"]},
{id:"at",name:"AT",phase:"Suivre + Traiter",tag:"Gérez les accidents du travail",icon:"+",start:52,end:68,desc:"Déclaration, enquête, arbre des causes, actions correctives et suivi des accidents du travail et maladies professionnelles.",features:["Déclaration","Enquête","Arbre des causes","TF / TG"]},
{id:"admin",name:"ADMIN",phase:"Transverse",tag:"Gouvernez la plateforme",icon:"⚙",start:0,end:14,desc:"Utilisateurs, rôles, audit log, sécurité, RGPD, SSO et configuration multi-tenant.",features:["RBAC","Audit log","RGPD","SSO"]},
{id:"lena",name:"Application LÉNA",phase:"Assistant",tag:"Interrogez votre risque",icon:"★",start:0,end:14,desc:"LÉNA interroge le contexte LENAXIS pour synthétiser les informations, expliquer les risques et orienter les actions.",features:["Langage naturel","Synthèse multi-modules","Sources","Aide à la décision"]}
];
const nav=()=>'<header class="topbar"><a class="brand" href="index.html"><img src="'+LOGO+'" alt="LENAXIS"></a><nav class="mainnav"><div class="navdrop"><button>Solutions⌄</button><div class="dropgrid">'+MODULES.map(m=>'<a href="'+m.id+'.html"><b>'+m.name+'</b><span>'+m.tag+'</span></a>').join('')+'</div></div><a href="index.html#industries">Industries⌄</a><a href="index.html#resources">Ressources⌄</a><a href="index.html#about">À propos⌄</a></nav><div class="rightnav"><span class="lang">◉ FR⌄</span><a class="demo" href="mailto:contact@lenaxis.fr">Demander une démo →</a></div></header>';
const trust=()=>'<div class="trust"><div class="trust-title">DES INDUSTRIELS LEADERS<br>NOUS FONT CONFIANCE</div><span>TotalEnergies</span><span>AIRBUS</span><span>ArcelorMittal</span><span>SANOFI</span><span>VEOLIA</span><i></i><b>-40%<small>d’incidents majeurs</small></b><b>+30%<small>de résilience opérationnelle</small></b><b>-50%<small>de temps d’audit</small></b></div>';
const footer=()=>'<footer class="footer"><img src="'+LOGO+'" alt="LENAXIS"><span>12 modules natifs · Application LÉNA</span><a href="solutions.html">Toutes les solutions →</a></footer>';
function icon(m,cls='sol-icon'){return m.logo?'<div class="'+cls+'"><img src="'+m.logo+'" alt="" style="width:80%;height:80%;object-fit:contain"></div>':'<div class="'+cls+'">'+m.icon+'</div>'}
function prime(v){const s=+v.dataset.start||0,e=+v.dataset.end||999;const go=()=>{try{v.currentTime=s;v.play().catch(()=>{})}catch(_){}};v.addEventListener('loadedmetadata',go);v.addEventListener('timeupdate',()=>{if(v.currentTime>=e){v.currentTime=s;v.play().catch(()=>{})}});if(v.readyState>=1)go()}
function modulePage(m){return nav()+'<main class="module-page"><section class="module-hero"><div class="module-copy"><div class="breadcrumbs"><a href="index.html">Accueil</a> › <a href="solutions.html">Solutions</a> › '+m.name+'</div><div class="titleline">'+icon(m,'bigicon')+'<div><div class="phase">'+m.phase+'</div><h1>'+m.name+'</h1></div></div><h2>'+m.tag+'</h2><p>'+m.desc+'</p><div class="module-cta"><a class="btn dark" href="mailto:contact@lenaxis.fr">Demander une démo →</a><a class="btn light" href="'+VIDEO+'" target="_blank"><span class="playdot">▶</span>Vidéo générale</a></div><div class="mini">'+m.features.map(f=>'<div>✓ '+f+'</div>').join('')+'</div></div><div class="device">'+(m.poster?'<img src="'+m.poster+'" alt="Écran '+m.name+'">':'')+'<video muted playsinline controls preload="metadata" data-start="'+m.start+'" data-end="'+m.end+'"><source src="'+VIDEO+'" type="video/mp4"></video><div class="video-label">Capsule '+m.name+' — extrait de Lenaxis FR.mp4</div></div></section><section class="detail"><div class="detailgrid">'+m.features.slice(0,3).map((f,i)=>'<article class="dcard"><h3>'+f+'</h3><p>'+['Même contexte de risque partagé avec les autres modules LENAXIS.','Données et constats rattachés aux sites, actifs et scénarios concernés.','Traçabilité des informations et des actions pour faciliter la décision.'][i]+'</p></article>').join('')+'</div></section><section class="related"><h2>Continuer dans LENAXIS</h2><div class="relatedgrid">'+MODULES.filter(x=>x.id!==m.id).slice(0,4).map(x=>'<a href="'+x.id+'.html">'+x.name+'<span>'+x.tag+'</span></a>').join('')+'</div></section>'+trust()+'</main>'+footer()}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('header')?.replaceWith(document.createRange().createContextualFragment(nav()));document.getElementById('footer')?.replaceWith(document.createRange().createContextualFragment(footer()));const id=document.body.dataset.module;if(id){const m=MODULES.find(x=>x.id===id);document.getElementById('app').innerHTML=modulePage(m)}if(document.body.dataset.page==='solutions'){document.getElementById('app').innerHTML=nav()+'<main class="module-page"><section class="section"><div class="section-head"><div class="kicker">SOLUTIONS</div><h2>Les 12 modules natifs LENAXIS + Application LÉNA.</h2><p>Un portefeuille intégré couvrant l’ensemble du cycle GRC industriel.</p></div><div class="grid">'+MODULES.map(m=>'<a class="sol" href="'+m.id+'.html">'+icon(m)+'<div class="phase">'+m.phase+'</div><h3>'+m.name+'</h3><b>'+m.tag+'</b><p>'+m.desc+'</p></a>').join('')+'</div></section></main>'+footer()}document.querySelectorAll('video[data-start]').forEach(prime);document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{const i=document.querySelector('.askline input');if(i){i.value=c.textContent.trim();i.focus()}}));document.querySelector('.askline button')?.addEventListener('click',()=>{const q=document.querySelector('.askline input')?.value.trim();if(q)location.href='lena.html?q='+encodeURIComponent(q)})});
